# Note: committed as a WIP, never got it to work (swicthing do docker compose instead)

kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-automation-persistent-volume
  labels:
    app: home-automation
    type: local
spec:
  storageClassName: home-automation-storage
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce   # one pod can write at a time
  hostPath:
    path: "/home/etauker/data/home-automation/hass"