# Note: committed as a WIP, never got it to work (swicthing do docker compose instead)

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-automation-persistent-volume-claim
  labels:
    app: home-automation
spec:
  storageClassName: home-automation-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce   # one pod can write at a time
  resources:
    requests:
      storage: 5Gi