version: '3'

services:
  mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
      - 9001:9001

  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: host
    depends_on: [ mosquitto ]
    restart: unless-stopped
    # user: mosquitto:hass
    privileged: true
    volumes:
      - ./data/hass:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    environment:
      - TZ=Europe/Dublin

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    network_mode: host
    depends_on: [ mosquitto ]
    restart: unless-stopped
    # user: mosquitto:hass
    # group_add:
    #   - dialout
    # user: 1000:1000
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Dublin
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyACM0

# TODO: implement
#   glances:
#     container_name: glances
#     image: nicolargo/glances:latest-full
#     restart: always
#     pid: host
#     volumes:
#       # - ./data/glances/passwd:/root/.config/glances/glances.pwd
#       # - ./data/glances/glances.conf:/glances/conf/glances.conf
#       - /var/run/docker.sock:/var/run/docker.sock:ro

#     ports:
#       - 61208:61208
#       - 61209:61209
#     environment:
#       - "GLANCES_OPT=-w --password"
#     secrets:
#       - source: glances_password
#         target: /root/.config/glances/glances.pwd

# secrets:
#   glances_password:
#     file: ./data/glances/passwd
