- platform: history_stats
  name: ${id}_time_on_today
  entity_id: switch.${id}
  unique_id: sensor.${id}_time_on_today
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: ${id}_time_on_this_month
  entity_id: switch.${id}
  unique_id: sensor.${id}_time_on_this_month
  state: "on"
  type: time
  start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"
