version: '3'

services:

  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    volumes:
      - ../data/hass:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Dublin
    networks:
      - home-automation
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.home-assistant.rule=Host(`dev.etauker.ie`) && (Path(`/auth/token`) || PathPrefix(`/home-assistant`) || HeadersRegexp(`Referer`, `https?://dev.etauker.ie/home-assistant.*`) || HeadersRegexp(`Referer`, `https?://dev.etauker.ie/lovelace.*`) || HeadersRegexp(`Referer`, `https?://dev.etauker.ie/auth/authorize.*`) || Path(`/api/websocket`))"
      - "traefik.http.routers.home-assistant.rule=Host(`hass.etauker.ie`)"
      - "traefik.http.routers.home-assistant.entrypoints=web,ws"
      - "traefik.http.middlewares.strip-home-assistant-prefix.stripprefix.prefixes=/home-assistant"
      - "traefik.http.routers.home-assistant.middlewares=strip-home-assistant-prefix@docker"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"

# networks:
#   home-automation:
#     name: home-automation
#     external: true

#   reverse-proxy:
#     name: traefik
#     external: true

