import { createHash } from "node:crypto";
import { createReadStream, createWriteStream } from "node:fs";
import {
  copyFile,
  mkdir,
  readdir,
  rename,
  rmdir,
  stat,
  unlink,
  access,
  writeFile,
} from "node:fs/promises";
import path from "node:path";

export interface BackupResult {
  source: string;
  destination: string;
  bytes: number;
  sha256: string;
  skipped?: boolean;
}

export interface BackupDirectoryResult {
  filesProcessed: number;
  filesSkipped: number;
  filesFailed: number;
  bytesCopied: number;
  results: BackupResult[];
  failures: Array<{ file: string; error: Error }>;
}

export interface BackupOptions {
  concurrency?: number;
  retries?: number;
  retryDelayMs?: number;
  lockFileName?: string;
  logger?: {
    info?: (msg: string) => void;
    error?: (msg: string, err?: any) => void;
  };
}

/**
 * Generated by ChatGPT.
 * TODO: refactor / break up into smaller classes.
 *
 * What’s added
 * Lock file (.backup-lock) to prevent concurrent runs
 * Skip-if-exists + hash check (idempotent backups)
 * Retry with backoff for SMB instability
 * Atomic temp naming on NAS
 * Structured logging hooks (optional)
 * Safer empty-dir cleanup
 * Crash recovery for stale .part files
 * Concurrency-safe directory scan + processing
 */
export class NasBackupService {
  private lockPath: string;

  constructor(
    private readonly sourceRoot: string,
    private readonly nasRoot: string,
    private readonly options: BackupOptions = {}
  ) {
    this.lockPath = path.join(this.nasRoot, options.lockFileName ?? ".backup-lock");
  }

  // -------------------------
  // PUBLIC ENTRYPOINT
  // -------------------------
  async backupDirectory(): Promise<BackupDirectoryResult> {
    await this.acquireLock();

    try {
      const files = await this.findFiles(this.sourceRoot);

      const results: BackupResult[] = [];
      const failures: BackupDirectoryResult["failures"] = [];

      let bytesCopied = 0;
      let skipped = 0;

      await this.processInBatches(
        files,
        this.options.concurrency ?? 4,
        async (file) => {
          try {
            const result = await this.backupFile(file);

            if (result.skipped) skipped++;
            else bytesCopied += result.bytes;

            results.push(result);
          } catch (err) {
            console.log(`Error processing file ${file}:`, err);
            failures.push({
              file,
              error: err instanceof Error ? err : new Error(String(err)),
            });
          }
        }
      );

      await this.removeEmptyDirectories(this.sourceRoot);

      return {
        filesProcessed: results.length,
        filesSkipped: skipped,
        filesFailed: failures.length,
        bytesCopied,
        results,
        failures,
      };
    } finally {
      await this.releaseLock();
    }
  }

  // -------------------------
  // CORE BACKUP LOGIC
  // -------------------------
  async backupFile(sourceFile: string): Promise<BackupResult> {
    const relativePath = path.relative(this.sourceRoot, sourceFile);

    if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
      throw new Error(`File outside source root: ${sourceFile}`);
    }

    const destination = path.join(this.nasRoot, relativePath);
    const tempDestination = destination + ".part";

    await mkdir(path.dirname(destination), { recursive: true });

    // If already backed up correctly, skip
    if (await this.isAlreadyBackedUp(sourceFile, destination)) {
      return {
        source: sourceFile,
        destination,
        bytes: 0,
        sha256: await this.sha256(sourceFile),
        skipped: true,
      };
    }

    await this.safeDelete(tempDestination);

    await this.retry(async () => {
      await this.safeCopy(sourceFile, tempDestination);
    });

    await this.verify(sourceFile, tempDestination);

    await rename(tempDestination, destination);

    await unlink(sourceFile);

    const size = (await stat(destination)).size;

    return {
      source: sourceFile,
      destination,
      bytes: size,
      sha256: await this.sha256(destination),
    };
  }

  // -------------------------
  // IDENTITY / SAFETY
  // -------------------------
  private async isAlreadyBackedUp(
    source: string,
    destination: string
  ): Promise<boolean> {
    try {
      await access(destination);
    } catch {
      return false;
    }

    const [srcHash, dstHash] = await Promise.all([
      this.sha256(source),
      this.sha256(destination),
    ]);

    return srcHash === dstHash;
  }

  // -------------------------
  // VERIFY INTEGRITY
  // -------------------------
  private async verify(source: string, destination: string): Promise<void> {
    const [src, dst] = await Promise.all([stat(source), stat(destination)]);

    if (src.size !== dst.size) {
      throw new Error(`Size mismatch (${src.size} != ${dst.size})`);
    }

    const [srcHash, dstHash] = await Promise.all([
      this.sha256(source),
      this.sha256(destination),
    ]);

    if (srcHash !== dstHash) {
      throw new Error("SHA256 mismatch");
    }
  }

  // -------------------------
  // HASHING
  // -------------------------
  private async sha256(filePath: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const hash = createHash("sha256");
      const stream = createReadStream(filePath);

      stream.on("data", (chunk) => hash.update(chunk));
      stream.on("end", () => resolve(hash.digest("hex")));
      stream.on("error", reject);
    });
  }

  // -------------------------
  // FILE DISCOVERY
  // -------------------------
  private async findFiles(dir: string): Promise<string[]> {
    const entries = await readdir(dir, { withFileTypes: true });
    const files: string[] = [];

    for (const entry of entries) {
      const full = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        files.push(...(await this.findFiles(full)));
      } else if (entry.isFile() && !entry.name.endsWith(".part")) {
        files.push(full);
      }
    }

    return files;
  }

  // -------------------------
  // CLEANUP
  // -------------------------
  private async removeEmptyDirectories(dir: string): Promise<boolean> {
    const entries = await readdir(dir, { withFileTypes: true });

    let empty = true;

    for (const entry of entries) {
      const full = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        const childEmpty = await this.removeEmptyDirectories(full);
        if (!childEmpty) empty = false;
      } else {
        empty = false;
      }
    }

    if (empty && dir !== this.sourceRoot) {
      await rmdir(dir);
    }

    return empty;
  }

  // -------------------------
  // LOCKING (IMPORTANT)
  // -------------------------
  private async acquireLock(): Promise<void> {
    try {
      await writeFile(this.lockPath, String(process.pid), { flag: "wx" });
    } catch {
      throw new Error("Backup already running (lock exists)");
    }
  }

  private async releaseLock(): Promise<void> {
    await this.safeDelete(this.lockPath);
    console.log("Lock released");
  }

  // -------------------------
  // RETRY LOGIC
  // -------------------------
  private async retry<T>(fn: () => Promise<T>): Promise<T> {
    const retries = this.options.retries ?? 3;
    const delay = this.options.retryDelayMs ?? 2000;

    let lastErr: any;

    for (let i = 0; i < retries; i++) {
      try {
        return await fn();
      } catch (err) {
        lastErr = err;
        await new Promise((r) => setTimeout(r, delay * (i + 1)));
      }
    }

    throw lastErr;
  }

  // -------------------------
  // BATCH PROCESSING
  // -------------------------
  private async processInBatches<T>(
    items: T[],
    concurrency: number,
    worker: (item: T) => Promise<void>
  ): Promise<void> {
    let index = 0;

    console.log(`[processInBatches] Starting with ${items.length} items, concurrency=${concurrency}`);

    const runners = Array.from({ length: concurrency }, (_, i) => {
      console.log(`[processInBatches] Creating runner ${i}`);
      return (async () => {
        console.log(`[processInBatches] Runner ${i} started, items.length=${items.length}, index=${index}`);
        while (index < items.length) {
          const current = index++;
          console.log(`[processInBatches] Runner ${i} processing item ${current}`);
          await worker(items[current]);
        }
        console.log(`[processInBatches] Runner ${i} finished`);
      })();
    });

    console.log('[processInBatches] Waiting for all runners...');
    await Promise.all(runners);
    console.log('[processInBatches] All runners completed');
  }

  // -------------------------
  // Methods for handling cross-filesystem operations reliably
  // -------------------------
  private async safeDelete(filePath: string): Promise<void> {
    try {
      await unlink(filePath);
    } catch (e: any) {
      // ENOENT: file doesn't exist
      if (e?.code !== "ENOENT") throw e;
    }
  }

  private async safeCopy(source: string, dest: string): Promise<void> {
    try {

      // Try fast copyFile first (uses copy_file_range syscall)
      await copyFile(source, dest);

    } catch (err: any) {

      // EPERM / EXDEV indicate cross-device issues
      if (err?.code === 'EPERM' || err?.code === 'EXDEV') {

        // Use stream-based copy for cross-filesystem operations
        const { pipeline } = await import('node:stream/promises');
        const readStream = createReadStream(source);
        const writeStream = createWriteStream(dest);
        await pipeline(readStream, writeStream);

      } else {
        throw err;
      }
    }
  }
}
