import { createHash } from "node:crypto";
import { createReadStream, createWriteStream } from "node:fs";
import {
  copyFile,
  mkdir,
  readdir,
  rename,
  rmdir,
  stat,
  unlink,
  access,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { Semaphore } from "./semaphore";
import type {
  BackupResult,
  BackupDirectoryResult,
  BackupOptions,
} from "./backup.interfaces";

export type { BackupResult, BackupDirectoryResult, BackupOptions };

/**
 * Generated by ChatGPT.
 * TODO: refactor / break up into smaller classes.
 *
 * What’s added
 * Lock file (.backup-lock) to prevent concurrent runs
 * Skip-if-exists + hash check (idempotent backups)
 * Retry with backoff for SMB instability
 * Atomic temp naming on NAS
 * Structured logging hooks (optional)
 * Safer empty-dir cleanup
 * Crash recovery for stale .part files
 * Concurrency-safe directory scan + processing
 */
export class NasBackupService {
  private lockPath: string;
  private semaphore: Semaphore;

  constructor(
    private readonly sourceRoot: string,
    private readonly nasRoot: string,
    private readonly options: BackupOptions = {}
  ) {
    this.lockPath = path.join(this.nasRoot, options.lockFileName ?? ".backup-lock");
    this.semaphore = new Semaphore(options.maxConcurrentBackups ?? 4);
  }

  // -------------------------
  // PUBLIC ENTRYPOINT
  // -------------------------
  async backupFile(sourceFile: string): Promise<BackupResult> {
    return await this.semaphore.acquire(async () => {
      const relativePath = path.relative(this.sourceRoot, sourceFile);

      if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
        throw new Error(`File outside source root: ${sourceFile}`);
      }

      const destination = path.join(this.nasRoot, relativePath);
      const lockPath = destination + ".lock";

      // Ensure parent directory exists before creating lock file
      await mkdir(path.dirname(destination), { recursive: true });

      await this.acquireFileLock(lockPath);
      try {
        const result = await this.copyAndVerify(sourceFile);

        // Clean up empty directories in source after successful backup
        // Note: sourceFile has already been deleted in copyAndVerify
        try {
          const sourceDir = path.dirname(sourceFile);
          await this.cleanupEmptyDirectories(sourceDir);
        } catch (cleanupError) {
          // Log but don't fail the backup if cleanup fails
          this.options.logger?.error?.(
            `Warning: Failed to cleanup empty directories after backing up ${sourceFile}`,
            cleanupError
          );
        }

        return result;
      } finally {
        await this.releaseFileLock(lockPath);
      }
    });
  }

  private async copyAndVerify(sourceFile: string): Promise<BackupResult> {
    const relativePath = path.relative(this.sourceRoot, sourceFile);

    if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
      throw new Error(`File outside source root: ${sourceFile}`);
    }

    const destination = path.join(this.nasRoot, relativePath);
    const tempDestination = destination + ".part";

    await mkdir(path.dirname(destination), { recursive: true });

    // If already backed up correctly, skip
    if (await this.isAlreadyBackedUp(sourceFile, destination)) {
      return {
        source: sourceFile,
        destination,
        bytes: 0,
        sha256: await this.sha256(sourceFile),
        skipped: true,
      };
    }

    await this.safeDelete(tempDestination);

    await this.retry(async () => {
      await this.safeCopy(sourceFile, tempDestination);
    });

    await this.verify(sourceFile, tempDestination);

    await rename(tempDestination, destination);

    await unlink(sourceFile);

    const size = (await stat(destination)).size;

    return {
      source: sourceFile,
      destination,
      bytes: size,
      sha256: await this.sha256(destination),
    };
  }

  // -------------------------
  // IDENTITY / SAFETY
  // -------------------------
  private async isAlreadyBackedUp(
    source: string,
    destination: string
  ): Promise<boolean> {
    try {
      await access(destination);
    } catch {
      return false;
    }

    const [srcHash, dstHash] = await Promise.all([
      this.sha256(source),
      this.sha256(destination),
    ]);

    return srcHash === dstHash;
  }

  // -------------------------
  // VERIFY INTEGRITY
  // -------------------------
  private async verify(source: string, destination: string): Promise<void> {
    const [src, dst] = await Promise.all([stat(source), stat(destination)]);

    if (src.size !== dst.size) {
      throw new Error(`Size mismatch (${src.size} != ${dst.size})`);
    }

    const [srcHash, dstHash] = await Promise.all([
      this.sha256(source),
      this.sha256(destination),
    ]);

    if (srcHash !== dstHash) {
      throw new Error("SHA256 mismatch");
    }
  }

  // -------------------------
  // HASHING
  // -------------------------
  private async sha256(filePath: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const hash = createHash("sha256");
      const stream = createReadStream(filePath);

      stream.on("data", (chunk) => hash.update(chunk));
      stream.on("end", () => resolve(hash.digest("hex")));
      stream.on("error", reject);
    });
  }

  // -------------------------
  // FILE DISCOVERY
  // -------------------------
  private async findFiles(dir: string): Promise<string[]> {
    const entries = await readdir(dir, { withFileTypes: true });
    const files: string[] = [];

    for (const entry of entries) {
      const full = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        files.push(...(await this.findFiles(full)));
      } else if (entry.isFile() && !entry.name.endsWith(".part")) {
        files.push(full);
      }
    }

    return files;
  }

  // -------------------------
  // CLEANUP
  // -------------------------
  /**
   * Recursively clean up empty directories starting from the given directory.
   * This is useful after backing up files to remove leftover empty folder structures.
   * 
   * Cleans in two phases:
   * 1. Downward: Removes empty subdirectories recursively
   * 2. Upward: Walks up to sourceRoot, removing newly-empty parent directories
   *
   * @param startDir - The directory to start cleaning from (works up towards sourceRoot)
   * @returns Promise that resolves when cleanup is complete
   */
  async cleanupEmptyDirectories(startDir?: string): Promise<void> {
    const dir = startDir || this.sourceRoot;

    // Validate that the directory is within sourceRoot
    const relativePath = path.relative(this.sourceRoot, dir);
    if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
      throw new Error(`Directory outside source root: ${dir}`);
    }

    this.options.logger?.info?.(`Cleaning up empty directories starting from: ${dir}`);
    
    // Phase 1: Clean downward (remove empty subdirectories)
    await this.removeEmptyDirectories(dir);
    
    // Phase 2: Clean upward (remove newly-empty parent directories)
    await this.cleanupParentDirectories(dir);
    
    this.options.logger?.info?.(`Empty directory cleanup complete`);
  }

  /**
   * Walk upward from a directory to sourceRoot, removing empty parent directories.
   * Stops when it reaches sourceRoot or encounters a non-empty directory.
   */
  private async cleanupParentDirectories(startDir: string): Promise<void> {
    const resolvedSourceRoot = path.resolve(this.sourceRoot);
    let currentDir = path.resolve(startDir);

    // Walk upward until we reach sourceRoot
    while (currentDir !== resolvedSourceRoot) {
      // Check if current directory exists
      try {
        await access(currentDir);
      } catch {
        // Directory doesn't exist anymore (already removed), move to parent
        currentDir = path.dirname(currentDir);
        continue;
      }

      // Check if directory is empty
      const entries = await readdir(currentDir, { withFileTypes: true });
      
      // Filter out lock and temp files
      const relevantEntries = entries.filter(entry => 
        !entry.name.endsWith('.lock') && !entry.name.endsWith('.part')
      );

      if (relevantEntries.length === 0) {
        // Directory is empty, remove it
        this.options.logger?.info?.(`Removing empty parent directory: ${currentDir}`);
        try {
          await rmdir(currentDir);
        } catch (err: any) {
          // If removal fails, log and stop walking upward
          this.options.logger?.error?.(`Failed to remove directory ${currentDir}`, err);
          break;
        }
      } else {
        // Directory is not empty, stop walking upward
        break;
      }

      // Move to parent directory
      currentDir = path.dirname(currentDir);
    }
  }

  private async removeEmptyDirectories(dir: string): Promise<boolean> {
    // Check if directory exists
    try {
      await access(dir);
    } catch {
      // Directory doesn't exist, nothing to clean
      return true;
    }

    const entries = await readdir(dir, { withFileTypes: true });

    let empty = true;

    for (const entry of entries) {
      const full = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        const childEmpty = await this.removeEmptyDirectories(full);
        if (!childEmpty) empty = false;
      } else {
        // Ignore lock files when determining if directory is empty
        if (!entry.name.endsWith('.lock') && !entry.name.endsWith('.part')) {
          empty = false;
        }
      }
    }

    if (empty && dir !== this.sourceRoot) {
      this.options.logger?.info?.(`Removing empty directory: ${dir}`);
      await rmdir(dir);
    }

    return empty;
  }

  // -------------------------
  // LOCKING (IMPORTANT)
  // -------------------------
  private async acquireLock(): Promise<void> {
    try {
      await writeFile(this.lockPath, String(process.pid), { flag: "wx" });
    } catch {
      throw new Error("Backup already running (lock exists)");
    }
  }

  private async releaseLock(): Promise<void> {
    await this.safeDelete(this.lockPath);
    console.log("Lock released");
  }

  private async acquireFileLock(lockPath: string): Promise<void> {
    try {
      await writeFile(lockPath, String(process.pid), { flag: "wx" });
    } catch (err: any) {
      // Check if lock file already exists
      if (err?.code === "EEXIST") {
        // Check if the lock is stale (process no longer running)
        const isStale = await this.isLockStale(lockPath);
        if (isStale) {
          // Remove stale lock and try again
          await this.safeDelete(lockPath);
          await writeFile(lockPath, String(process.pid), { flag: "wx" });
          console.log(`Removed stale lock and acquired: ${lockPath}`);
          return;
        }
        throw new Error(`File already being backed up (lock exists): ${lockPath}`);
      }
      // Any other error (e.g., permission issues) - rethrow with context
      throw new Error(`Failed to acquire lock at ${lockPath}: ${err.message}`);
    }
  }

  private async releaseFileLock(lockPath: string): Promise<void> {
    await this.safeDelete(lockPath);
  }

  /**
   * Check if a lock file is stale (the process that created it is no longer running).
   * This prevents orphaned locks from blocking backups after crashes.
   */
  private async isLockStale(lockPath: string): Promise<boolean> {
    try {
      const pidStr = await import("node:fs/promises").then((fs) =>
        fs.readFile(lockPath, "utf-8")
      );
      const pid = parseInt(pidStr.trim(), 10);

      if (isNaN(pid)) {
        // Invalid PID in lock file - consider it stale
        return true;
      }

      // Check if process is still running
      // On Unix, kill(pid, 0) checks if process exists without actually killing it
      try {
        process.kill(pid, 0);
        return false; // Process exists, lock is valid
      } catch (err: any) {
        // ESRCH = no such process, lock is stale
        // EPERM = process exists but we don't have permission to signal it
        return err.code === "ESRCH";
      }
    } catch {
      // Can't read lock file - consider it stale
      return true;
    }
  }

  // -------------------------
  // RETRY LOGIC
  // -------------------------
  private async retry<T>(fn: () => Promise<T>): Promise<T> {
    const retries = this.options.retries ?? 3;
    const delay = this.options.retryDelayMs ?? 2000;

    let lastErr: any;

    for (let i = 0; i < retries; i++) {
      try {
        return await fn();
      } catch (err) {
        lastErr = err;
        await new Promise((r) => setTimeout(r, delay * (i + 1)));
      }
    }

    throw lastErr;
  }

  // -------------------------
  // BATCH PROCESSING
  // -------------------------
  private async processInBatches<T>(
    items: T[],
    concurrency: number,
    worker: (item: T) => Promise<void>
  ): Promise<void> {
    let index = 0;

    console.log(`[processInBatches] Starting with ${items.length} items, concurrency=${concurrency}`);

    const runners = Array.from({ length: concurrency }, (_, i) => {
      console.log(`[processInBatches] Creating runner ${i}`);
      return (async () => {
        console.log(`[processInBatches] Runner ${i} started, items.length=${items.length}, index=${index}`);
        while (index < items.length) {
          const current = index++;
          console.log(`[processInBatches] Runner ${i} processing item ${current}`);
          await worker(items[current]);
        }
        console.log(`[processInBatches] Runner ${i} finished`);
      })();
    });

    console.log('[processInBatches] Waiting for all runners...');
    await Promise.all(runners);
    console.log('[processInBatches] All runners completed');
  }

  // -------------------------
  // Methods for handling cross-filesystem operations reliably
  // -------------------------
  private async safeDelete(filePath: string): Promise<void> {
    try {
      await unlink(filePath);
    } catch (e: any) {
      // ENOENT: file doesn't exist
      if (e?.code !== "ENOENT") throw e;
    }
  }

  private async safeCopy(source: string, dest: string): Promise<void> {
    try {

      // Try fast copyFile first (uses copy_file_range syscall)
      await copyFile(source, dest);

    } catch (err: any) {

      // EPERM / EXDEV indicate cross-device issues
      if (err?.code === 'EPERM' || err?.code === 'EXDEV') {

        // Use stream-based copy for cross-filesystem operations
        const { pipeline } = await import('node:stream/promises');
        const readStream = createReadStream(source);
        const writeStream = createWriteStream(dest);
        await pipeline(readStream, writeStream);

      } else {
        throw err;
      }
    }
  }
}
